# Generated by Django 6.0.2 on 2026-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('UTILITY', 'Utility'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
