# Generated by Django 6.0.2 on 2026-02-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_spare_parts_and_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Quantity at which to reorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock keeping unit', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, help_text='OEM number', max_length=50),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.carmake')),
            ],
            options={
                'unique_together': {('make', 'name', 'year_from', 'year_to')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatibilities',
            field=models.ManyToManyField(blank=True, help_text='Vehicle models this part fits', related_name='compatible_products', to='inventory.carmodel'),
        ),
    ]
