# Generated by Django 6.0.2 on 2026-02-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_cost_price_alter_product_brand_and_more'),
        ('sales', '0003_alter_sale_payment_method_alter_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
