# Generated by Django 6.0.2 on 2026-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
    ]
