# Generated by Django 6.0.3 on 2026-03-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_customer_and_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Accumulated loyalty points'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('ATM', 'ATM'), ('TRANSFER', 'Bank Transfer'), ('MOBILE', 'Mobile Payment'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Points earned (positive) or spent (negative)')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earned'), ('SPEND', 'Spent')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale that triggered the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
            ],
        ),
    ]
